name: CI - Build and Test
on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.11.0'   
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        modules: 'qtwebsocketsوQt6Network وQt6SerialPort'  
        tools: 'tools_ifw,qtcmake'
        set-env: true

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Configure and Build with CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" 
        cmake --build . --config Release --parallel

   
    - name: Run Unit Tests
      run: |
        cd build
        ctest -C Release --output-on-failure
